import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="quasar",
    version="0.0.0",
    author="QC Ware Corp.",
    author_email="",
    description="Quasar: an ultralight python-2.7/python-3.X quantum circuit simulator package.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/qcware/quasar",
    packages=setuptools.find_packages(),
    package_data={'': ['*.dat']},
    install_requires=[
        "antlr4-python3-runtime==4.7.2",
        "asn1crypto==0.24.0",
        "backcall==0.1.0",
        "cachetools==3.1.1",
        "certifi==2019.6.16",
        "cffi==1.12.3",
        "chardet==3.0.4",
        "cirq==0.5.0",
        "cryptography==2.7",
        "cycler==0.10.0",
        "decorator==4.4.0",
        "future==0.17.1",
        "google-api-python-client==1.7.9",
        "google-auth==1.6.3",
        "google-auth-httplib2==0.0.3",
        "httplib2==0.13.0",
        "idna==2.8",
        "immutables==0.6",
        "ipykernel==5.1.1",
        "ipython==7.6.1",
        "ipython-genutils==0.2.0",
        "jedi==0.14.1",
        "jsonschema==2.6.0",
        "jupyter-client==5.3.1",
        "jupyter-core==4.5.0",
        "kiwisolver==1.1.0",
        "marshmallow==2.19.5",
        "marshmallow-polyfield==3.2",
        "matplotlib==2.2.4",
        "mpmath==1.1.0",
        "msgpack==0.6.1",
        "networkx==2.3",
        "ntlm-auth==1.3.0",
        "numpy==1.16.4",
        "parso==0.5.1",
        "pexpect==4.7.0",
        "pickleshare==0.7.5",
        "Pillow==6.1.0",
        "ply==3.11",
        "prompt-toolkit==2.0.9",
        "protobuf==3.9.0",
        "psutil==5.6.3",
        "ptyprocess==0.6.0",
        "pyasn1==0.4.5",
        "pyasn1-modules==0.2.5",
        "pycparser==2.19",
        "Pygments==2.4.2",
        "pyparsing==2.4.0",
        "pyquil==2.9.1",
        "python-dateutil==2.8.0",
        "python-rapidjson==0.7.2",
        "pytz==2019.1",
        "pyzmq==18.0.2",
        "qiskit==0.7.1",
        "qiskit-aer==0.1.1",
        "qiskit-terra==0.7.2",
        "requests==2.22.0",
        "requests-ntlm==1.1.0",
        "rpcq==2.7.1",
        "rsa==4.0",
        "ruamel.yaml==0.15.100",
        "scipy==1.3.0",
        "six==1.12.0",
        "sortedcontainers==2.1.0",
        "sympy==1.4",
        "tornado==6.0.3",
        "traitlets==4.3.2",
        "typing==3.7.4",
        "typing-extensions==3.7.4",
        "uritemplate==3.0.0",
        "urllib3==1.25.3",
        "wcwidth==0.1.7",
        "importlib_resources==1.0.4"],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
)
