 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "===Starting Test==="
       - run: export PYTHONPATH=~/quasar
       - run: python test/utest/simple_test.py
       - run: python test/utest/utest.py
