 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.6.4  # primary container for the build job
     environment:
       PYTHONPATH: /home/circleci/project
     steps:
       - checkout
       - run: echo "===Starting Test==="
       - run:
          command: |  # use pipenv to install dependencies
            sudo pip install -e .[ionq]
       - run: python -m unittest discover -s 'test/utest'
