 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     environment:
       PYTHONPATH: /home/circleci/project
     steps:
       - checkout
       - run: 
           command: |
           echo 'export PYTHONPATH="/home/circleci/project"' >> $BASH_ENV
       - run: echo "===Starting Test==="
       - run: pwd
       - run: ls
       - run: python test/utest/simple_test.py
       - run: python test/utest/utest.py
