 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     environment:
       PYTHONPATH: /home/circleci/project
     steps:
       - checkout
       - run: echo "===Starting Test==="
         command: |
             sudo pip install -r requirements.txt
       - run: pwd
       - run: ls
       - run: python test/utest/simple_test.py
       - run: python test/utest/utest.py
