import quasar

circuit = quasar.Circuit()

print(circuit.gates)
print(circuit.ngate)
print(circuit.ngate1)
print(circuit.ngate2)
print(circuit.max_gate_nqubit)
print(circuit.min_qubit)
print(circuit.max_qubit)
print(circuit.nqubit)
print(circuit.nqubit_sparse)
print(circuit.min_time)
print(circuit.max_time)
print(circuit.ntime)
print(circuit.ntime_sparse)
print('')

circuit = quasar.Circuit().add_gate(quasar.Gate.H, 0).add_gate(quasar.Gate.CX, (0,1)).add_gate(quasar.Gate.CX, (1,2))

print(circuit.gates)
print(circuit.ngate)
print(circuit.ngate1)
print(circuit.ngate2)
print(circuit.max_gate_nqubit)
print(circuit.min_qubit)
print(circuit.max_qubit)
print(circuit.nqubit)
print(circuit.nqubit_sparse)
print(circuit.min_time)
print(circuit.max_time)
print(circuit.ntime)
print(circuit.ntime_sparse)
print('')

circuit = quasar.Circuit().add_gate(quasar.Gate.H, 1).add_gate(quasar.Gate.CX, (1,2)).add_gate(quasar.Gate.CX, (2,3))

print(circuit.gates)
print(circuit.ngate)
print(circuit.ngate1)
print(circuit.ngate2)
print(circuit.max_gate_nqubit)
print(circuit.min_qubit)
print(circuit.max_qubit)
print(circuit.nqubit)
print(circuit.nqubit_sparse)
print(circuit.min_time)
print(circuit.max_time)
print(circuit.ntime)
print(circuit.ntime_sparse)
print('')
